### PR TITLE
WIP: giflib [skip appveyor]

### PR DESCRIPTION
**Pull request by ocefpaf**
Waiting for https://github.com/conda-forge/gdal-feedstock/pull/19

### CODE REVIEW

**Comment by pelson** [comment]
How will you know it is fixed? It would be healthy to add a test somehow (otool on the dylib maybe).

**Comment by ocefpaf** [comment]
> How will you know it is fixed? It would be healthy to add a test somehow (otool on the dylib maybe).

I won't. We do need a better system to assert links. Let's leave this one open for a while.

**Comment by pelson** [comment]
I'm not sure I agree. Fiona *does* depend on giflib doesn't it? I thought I was seeing that in the link:

```
dlopen(/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/ogrext.so, 2):
    Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
```

That is coming from a fiona shared object - does that not mean it also *needs* giflib?

**Comment by ocefpaf** [comment]
You are correct. I missed https://github.com/conda-forge/gdal-feedstock/issues/16#issuecomment-201949312. (Too many MTN PRs today!)

**Comment by pelson** [comment]
>  (Too many MTN PRs today!)

I only did 50! There are more than that needed :wink: 
Honestly though, you needn't merge everybody's MNT PRs - that is why there are multiple maintainers of feedstocks :smile:

**Comment by ocefpaf** [comment]
I left some unmerged to maintainers that I hope will be power players in conda-forge. But I merged those where I was the only maintainer and/or I had some interested due to upcoming changes. (Unfortunately that summed up to a lot of PRs!)

**Comment by pelson** [comment]
I'll hold fire on the rest of them for a day or two :smile:

**Pull request closed without merging**
