### PR TITLE
Rebuild for python 3.10

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

try using zip tree from upstream git repo tag.

### CODE REVIEW

**Comment by akrherz** [comment]
Interesting, python 3.7 error appears to be:

> 2021-11-30T01:55:52.4613879Z pkg_resources.DistributionNotFound: The 'certifi' distribution was not found and is required by the application

awaiting CI to return on others and will try to resolve that

**Comment by akrherz** [comment]
Oh my, windows build error is more "fun"
```
2021-11-30T02:03:06.4995920Z   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\bld\fiona_1638237385410\_h_env\libs /LIBPATH:D:\bld\fiona_1638237385410\_h_env\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64 /LIBPATH:D:\bld\fiona_1638237385410\_h_env\Library\lib /LIBPATH:D:\bld\fiona_1638237385410\_h_env\Library\lib /EXPORT:PyInit__geometry build\temp.win-amd64-3.10\Release\fiona/_geometry.obj /OUT:build\lib.win-amd64-3.10\fiona\_geometry.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\fiona\_geometry.cp310-win_amd64.lib
2021-11-30T02:03:06.5020273Z      Creating library build\temp.win-amd64-3.10\Release\fiona\_geometry.cp310-win_amd64.lib and object build\temp.win-amd64-3.10\Release\fiona\_geometry.cp310-win_amd64.exp
2021-11-30T02:03:06.5021119Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetGeometryType
2021-11-30T02:03:06.5021715Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_AddPoint_2D
2021-11-30T02:03:06.5022261Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetCoordinateDimension
2021-11-30T02:03:06.5022858Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetGeometryCount
2021-11-30T02:03:06.5023413Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetX
2021-11-30T02:03:06.5023921Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetY
2021-11-30T02:03:06.5024481Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetPointCount
2021-11-30T02:03:06.5025099Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_DestroyGeometry
2021-11-30T02:03:06.5030043Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_ImportFromWkb
2021-11-30T02:03:06.5030630Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_AddGeometryDirectly
2021-11-30T02:03:06.5031172Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_CreateGeometry
2021-11-30T02:03:06.5031722Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetZ
2021-11-30T02:03:06.5032227Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_AddPoint
2021-11-30T02:03:06.5032778Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_GetGeometryRef
2021-11-30T02:03:06.5033333Z   _geometry.obj : error LNK2001: unresolved external symbol OGR_G_CloseRings
```

**Comment by akrherz** [comment]
Hi @mattip, do you have thoughts on this PR's approach?

**Comment by akrherz** [comment]
Good heavens, @jorisvandenbossche and @ocefpaf, this PR is somehow green!  I can certainly squash/rebase to tidy up the commits if this change is of interest.  Additionally, I have a PR inbound to Fiona upstream attempting a formal 1.8.21 release with python 3.10 support (if/when I can get CI green there :))

**Comment by mattip** [comment]
For reviewers: the approach used is to download the git tarball (with sources) rather than the pypi sdist tarball (with precompiled cython c-files), and to build with
```
%PYTHON% setup.py build_ext
```

I think conda-forge has moved to deprecate [use of certifi](https://github.com/Toblerity/Fiona/search?q=certifi&type=code), I don't know if that is a blocker.

**Comment by akrherz** [comment]
I got an initial positive response for the upstream Fiona PR, so this change may or may not be necessary.  I would be happy to undo this change with a subsequent PR when a new formal Fiona release is made.

**Comment by ocefpaf** [comment]
Than you for fixing it! I just wanted to add extra dependencies only where we really needed them. py>37 is passing without certifi. so I remove it from them.

**Pull request merged**
