### PR TITLE
fiona 1.8a1

### PR DESCRIPTION
**Pull request by ocefpaf**
This is failing the big int test locally :unamused:

### CODE REVIEW

**Comment by ocefpaf** [comment]
1 test failing on Linux:

```
=========================== short test summary info ============================
XFAIL tests/test_unicode.py::UnicodeStringFieldTest::test_write_mismatch
  OGR silently fails to convert strings
SKIP [1] tests/test_binary_field.py:20: Requires geopackage fixture

=================================== FAILURES ===================================
______________________ TestBigInt.testCreateBigIntSchema _______________________

self = <tests.test_bigint.TestBigInt testMethod=testCreateBigIntSchema>

    def testCreateBigIntSchema(self):
        name = os.path.join(self.tempdir, 'output1.shp')
    
        a_bigint = 10 ** 18 - 1
        fieldname = 'abigint'
    
        kwargs = {
            'driver': 'ESRI Shapefile',
            'crs': 'EPSG:4326',
            'schema': {
                'geometry': 'Point',
                'properties': [(fieldname, 'int:10')]}}
        if get_gdal_version_num() < calc_gdal_version_num(2, 0, 0):
            with self.assertRaises(OverflowError):
                with fiona.open(name, 'w', **kwargs) as dst:
                    rec = {}
                    rec['geometry'] = {'type': 'Point', 'coordinates': (0, 0)}
                    rec['properties'] = {fieldname: a_bigint}
                    dst.write(rec)
        else:
    
            with fiona.open(name, 'w', **kwargs) as dst:
                rec = {}
                rec['geometry'] = {'type': 'Point', 'coordinates': (0, 0)}
                rec['properties'] = {fieldname: a_bigint}
>               dst.write(rec)

tests/test_bigint.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/feedstock_root/build_artefacts/fiona_1510063496093/_t_env/lib/python3.6/site-packages/fiona/collection.py:341: in write
    self.writerecords([record])
/feedstock_root/build_artefacts/fiona_1510063496093/_t_env/lib/python3.6/site-packages/fiona/collection.py:335: in writerecords
    self.session.writerecs(records, self)
fiona/ogrext.pyx:1023: in fiona.ogrext.WritingSession.writerecs
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OverflowError: value too large to convert to int

fiona/ogrext.pyx:304: OverflowError
=============================== warnings summary ===============================
tests/test_collection.py::PointWritingTest::test_cpg
  /tmp/tests/test_collection.py:375: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmplqs6wktg/point_writing_test.cpg' mode='r' encoding='UTF-8'>
    self.tempdir, "point_writing_test.cpg")).readline() == 'UTF-8')

tests/test_drivers.py::test_options
  /tmp/tests/test_drivers.py:28: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-root/pytest-0/test_options0/tests/test_options.log' mode='r' encoding='UTF-8'>
    log = open(logfile).read()

tests/test_fio_calc.py::test_calc_seq
  /feedstock_root/build_artefacts/fiona_1510063496093/_t_env/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
    return f(*args, **kwds)

tests/test_geopackage.py::test_read_gpkg
  /tmp/tests/test_geopackage.py:15: DeprecationWarning: Collection.__next__() is buggy and will be removed in Fiona 2.0. Switch to `next(iter(collection))`.
    feature = next(src)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================== 1 tests deselected ==============================
 1 failed, 604 passed, 1 skipped, 1 deselected, 1 xfailed, 5 xpassed, 4 warnings in 18.65 seconds 
Exited with code 1
```

@sgillies do you have any advice on what may be the culprit there?

**Comment by ocefpaf** [comment]
@snorfalorpagus if you have some free time could you take a look at our logs and see if I am missing something obvious. Only the `TestBigInt.testCreateBigIntSchema` is failing.

**Comment by snorfalorpagus** [comment]
@ocefpaf I can reproduce this on Windows (after setting `GDAL_VERSION=2.2.2` in `bld.bat`). I'll look into it.

**Comment by ocefpaf** [comment]
> I've been working on Fiona recently and this test passes in my environment, so there must be something about the recipe environment that is causing the problem.

Probably the way we build `gdal` or its dependencies... This one will be though to debug :unamused:

**Comment by sgillies** [comment]
It's odd that this is occurring only with GDAL 2.2. I've seen it as well when building the macosx wheels for PyPI. I've created an issue in the Fiona repo.

**Comment by snorfalorpagus** [comment]
I've just tried building this recipe against master and it seems to work. There are 2 failures, but they're due to some unrelated issues in the master branch. The big int test is no longer failing. I have no idea why the 1.8a1 is failing.
```
  git_url: https://github.com/Toblerity/Fiona.git
  git_rev: 99fa8c27e6f8f8d1dba428fe123878cf9bb5bba3
```

For this to work you also need to add two package dependencies (packaging for tests only I think):
```
    - boto3
    - packaging
```

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by jorisvandenbossche** [comment]
Quickly looking at the travis failure: the build is terminated because the log was exceeding 4 Mb, so it is not necessarily "really" failing. 
In the visible part, there are no failing tests. There are a lot of debug errors and warnings printed though, so that might certainly be an indication of something going wrong. Many of them seem to be related to botocore, with connection time outs / failures.

**Comment by jorisvandenbossche** [comment]
And appveyor failed because it reached the built time limit of 110 min, from the log it seems it was just finishing the tests (no failures, but also a lot of output as with travis).

**Comment by ocefpaf** [comment]
@jorisvandenbossche moving the OS X builds to CircleCI "fixed" them.
I'll investigate why Windows seems to be hanging later today (there is also a dependency issue I want to solve to get Python 3.7 built too).

**Comment by jorisvandenbossche** [comment]
The windows ones don't seem to be hanging, there is a dependency problem on installation that causes the build to error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal=2.2 -> numpy[version='>=1.11'] -> blas==1.1=openblas -> openblas -> libflang -> vc==14
  - gdal=2.2 -> numpy[version='>=1.11'] -> python[version='>=3.5,<3.6.0a0']
  - python=2.7
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ocefpaf** [comment]
> The windows ones don't seem to be hanging, there is a dependency problem on installation that causes the build to error:

That dependency problems is another issue. I cancelled the hanging ones b/c they are timing out.

**Comment by ocefpaf** [comment]
Windows+Python 2.7 won't get build this round b/c `conda-forge` does not have a `numpy` version available there, but we don't care about it in this PR, which is aimed at building the Python 3.7 version. Next re-render will restore `defaults` and all the Windows matrix items will build accordingly.

**Pull request merged**
