### PR TITLE
Cleanup / Improve GDAL dependencies

### LINKED ISSUE #234: Change fiona's GDAL dependency
### Comment:

Presently, `fiona` gets a GDAL dependency like so:

```
gdal
libgdal >=3.10.0,<3.11.0a0
libgdal-core >=3.10.0,<3.11.0a0
```

This is sub-optimal as `gdal` has no pin and `libgdal` is the kitchen sink vs `libgdal-core` and any necessary plugins.  Looking at the current `fiona` generated shared objects, I only see links to `libgdal.so.36`, but I also notice that we are not getting postgresql support, which should be added.  So I will be submitting a PR in this space and would appreciate any thoughts on this isssue...

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is a bit of an exploratory PR to figure out the bits of GDAL we need and bits of GDAL we should be adding

closes #234
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
# Observation 1

I don't think `fiona` needs the `gdal` package.  It does not use the python bindings nor calls GDAL's command line programs, does it?

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
# Observation 2

I think adding postgresql/postgis support out of the box would be good, it is unclear yet how to enable :)

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Eh, I am confused about how dependencies work again and what I did for libgdal-pg is not right.  Backing out that commit and this PR can be considered for merging / more discussion ...

**Review by xylar — APPROVED** [review]
I'm pretty new to maintaining fiona but looks reasonable to me.

**Review by ocefpaf — APPROVED** [review]

**Pull request merged**
