### PR TITLE
Remove skipped tests that no longer need to be skipped

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
No idea why `test_listdir_zipmemoryfile` is still failing, as the patch should be included in fiona 1.9.1 (https://github.com/Toblerity/Fiona/commit/bc32d5e57f87a2147468e5ded25925055a675f5b),  while the printed output from pytest shows the test code without the changes (so from an older fiona version)

**Comment by akrherz** [comment]
rebased and will rerender

@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Oh my, dependency problem
```
- Encountered problems while solving:
  - package shapely-1.8.0-py310hc0568fc_2 requires geos >=3.10.0,<3.10.1.0a0, but none of the providers can be installed
 ```

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
```
 __________________________ test_listdir_zipmemoryfile __________________________
 
 bytes_coutwildrnp_zip = b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xf5h;J\xfaug8\x05\n\x00\x00\xe1\xa8\x00\x00\x0f\x00\x1c\x00coutwildrnp.dbfUT\t\x0...0\x01\x04\xe8\x03\x00\x00\x04d\x00\x00\x00PK\x05\x06\x00\x00\x00\x00\x04\x00\x04\x00T\x01\x00\x00(\xae\x00\x00\x00\x00'
 
     def test_listdir_zipmemoryfile(bytes_coutwildrnp_zip):
         """Test list directories of a zipped memory file."""
         with ZipMemoryFile(bytes_coutwildrnp_zip) as memfile:
 >           assert memfile.listdir() == [
                 "coutwildrnp.shp",
                 "coutwildrnp.shx",
                 "coutwildrnp.dbf",
                 "coutwildrnp.prj",
             ]
 E           AssertionError: assert ['coutwildrnp...twildrnp.shx'] == ['coutwildrnp...twildrnp.prj']
 E             At index 0 diff: 'coutwildrnp.dbf' != 'coutwildrnp.shp'
 E             Full diff:
 E             - ['coutwildrnp.shp', 'coutwildrnp.shx', 'coutwildrnp.dbf', 'coutwildrnp.prj']
 E             + ['coutwildrnp.dbf', 'coutwildrnp.prj', 'coutwildrnp.shp', 'coutwildrnp.shx']

 tests/test_memoryfile.py:379: AssertionError
```

**Comment by akrherz** [comment]
Upstream patch submitted Toblerity/Fiona#1296

**Comment by akrherz** [comment]
The transient fun never stops!
```
 conda.CondaMultiError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/conda-forge/linux-64/gcc_impl_linux-aarch64-12.3.0-hfb0b921_2.conda
   target_path: /home/conda/feedstock_root/build_artifacts/pkg_cache/gcc_impl_linux-aarch64-12.3.0-hfb0b921_2.conda
   Content-Length: 324691291
   downloaded bytes: 194529697
```

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

rebased this again, will just take it, if green...

**Pull request merged**
