### PR TITLE
update cython version for python3.10

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

xref #185

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
I am unsure how this patch would work?  The version of cython is controlled via this feedstock repo, right?

**Comment by mattip** [comment]
The build.sh and bld.bat use `pip install --no-deps --ignore-installed`. I am not sure what happens with the dependencies: are the ones from conda used or are fresh dependencies downloaded? The actual build is not recorded in the logs.

**Comment by mattip** [comment]
The source tarball available at https://pypi.io/packages/source/F/Fiona/Fiona-1.8.20.tar.gz does not have the pyproject.toml file, so no wonder this PR is failing to patch. Closing.

**Pull request closed without merging**
