### PR TITLE
re-enable windows test, bump build

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Picks up where #193 left off, re-enabling the windows tests.

### CODE REVIEW

**Comment by akrherz** [comment]
Example windows build test output

> = 1487 passed, 9 skipped, 9 deselected, 2 xfailed, 7 xpassed, 45 warnings in 33.38s =

**Comment by jorisvandenbossche** [comment]
Great!

**Comment by akrherz** [comment]
@jorisvandenbossche can this PR be merged?

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Gonna take this, if CI passes.

**Comment by akrherz** [comment]
@jorisvandenbossche can this PR be merged?

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Review by zklaus — APPROVED** [review]
LGTM. More tests are better than fewer tests.

**Pull request merged**
