### PR TITLE
Rebuild for new fontconfig macOS dylib compatibility version

### PR DESCRIPTION
**Pull request by martinfleis**
I believe that rebuilding Fiona should resolve current installation issues on macOS (see https://github.com/conda-forge/fontconfig-feedstock/issues/54 and https://github.com/conda-forge/fontconfig-feedstock/pull/53#issuecomment-1062456875) and the issue itself for example in https://github.com/geopandas/geopandas/runs/5699959207?check_suite_focus=true

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Review by akrherz — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
It seems this rebuild has caused import issues -> https://github.com/conda-forge/fiona-feedstock/issues/192

**Comment by jorisvandenbossche** [comment]
I am also not sure if we actually run tests on Windows, at least the log does not have any output for the test step: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=481521&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=1252 (while eg on Mac you see the output of pytest)

**Comment by dopplershift** [comment]
@jorisvandenbossche It would seem the tests for Windows are currently commented out 😒

https://github.com/conda-forge/fiona-feedstock/blob/8e724f2f2c619ce39c19c6dfd7ee8df6f138cf7e/recipe/run_test.bat#L6-L7

**Comment by jorisvandenbossche** [comment]
Ah, that's the "REM" ..

Would it be possible to "cancel" the latest build so people would still get the previous working one, until we figure out the reason?

**Comment by dopplershift** [comment]
Open a PR [here](https://github.com/conda-forge/admin-requests) to mark the bad packages as "broken".

**Pull request merged**
